server:
  port: 80
spring:
  application:
    name: order80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群版
ribbon:
  ReadTimeout: 5000 # 建立连接用的时间
  ConnecTimeout: 5000# 建立服务到读取可用资源所用时间
logging:
  level:
    root: debug
