server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabitmq:
                host: localhost
                port: 5672
                username: guest
                passwoard: guest
      bindings:
        output:
          destination: studyExchange
          content-type: application/json
          bind: defaultRabbit

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群版
management:
  endpoints:
    web:
      exposure:
        include: "*"
