server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh # 路由id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由
            - After=2020-03-09T00:02:06.044+08:00[Asia/Shanghai]
            #- Cookie=name,ccc
           # - Header=X-Request-Id,\d+
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过来工厂会在匹配的请求头上加一堆请求头，名称为X-Request值为1024

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群版