server:
  port: 8802

spring:
  application:
    name: cloud-stream-consum
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabitmq:
                host: localhost
                port: 5672
                username: guest
                passwoard: guest
      bindings:
        input:
          destination: studyExchange
          content-type: application/json
          bind: defaultRabbit
          group: aaa

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群版
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    instance-id: receive-8802.com
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
